# Generated by Django 5.1.4 on 2025-01-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartx_cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
    ]
