# Generated by Django 5.1.4 on 2025-01-14 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kartx_cart', '0002_cart_user_cartitem_visible_alter_cartitem_cart'),
        ('kartx_cart', '0002_remove_cartitem_product_cartitem_product_id_and_more'),
    ]

    operations = [
    ]
