# Generated by Django 5.1.4 on 2025-01-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartx_cart', '0002_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
