# Generated by Django 5.1.4 on 2025-01-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartx_cart', '0005_remove_address_is_default_remove_address_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
