# Generated by Django 5.1.4 on 2025-01-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kartx_cart', '0008_remove_address_address_line_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_key',
        ),
    ]
