# Generated by Django 5.1.4 on 2025-01-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kartx_cart', '0010_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
