# Generated by Django 5.1.4 on 2025-01-13 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial'),
        ('accounts', '0004_user_groups_user_is_active_user_is_superuser_and_more'),
    ]

    operations = [
    ]
