# Generated by Django 5.1.4 on 2025-01-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20250113_0638'),
        ('accounts', '0006_rename_is_admin_user_is_staff_user_groups_and_more'),
    ]

    operations = [
    ]
