# Generated by Django 5.1.4 on 2025-01-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_userprofile_user_alter_order_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='approved',
        ),
    ]
