# Generated by Django 5.1.4 on 2025-01-15 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='approved',
        ),
    ]
