# Generated by Django 5.1.4 on 2025-01-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_name'),
        ('catalog', '0004_userprofile'),
    ]

    operations = [
    ]
