# Generated by Django 5.1.4 on 2025-01-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_salessummary_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
    ]
