# Generated by Django 5.1.4 on 2025-01-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_razorpayorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='razorpayorder',
            old_name='status',
            new_name='payment_status',
        ),
        migrations.AlterField(
            model_name='razorpayorder',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payment.cart'),
        ),
    ]
