# Generated by Django 5.1.4 on 2025-01-15 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartx_cart', '0003_alter_cartitem_cart'),
        ('payment', '0003_rename_status_razorpayorder_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpayorder',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kartx_cart.cart'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='razorpayorder',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='razorpayorder',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='razorpayorder',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='razorpayorder',
            name='payment_status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=50),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
